version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "danieleschmidt"
    assignees:
      - "danieleschmidt"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
          - "sphinx*"
          - "pre-commit*"
      production-dependencies:
        patterns:
          - "numpy*"
          - "scipy*"
          - "torch*"
          - "matplotlib*"
          - "plotly*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5