version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "numpy*"
          - "scipy*"
          - "torch*"
          - "matplotlib*"
          - "pytest*"
          - "ruff*"
          - "mypy*"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5