name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Acousto-Gen Version
      description: What version of Acousto-Gen are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Ubuntu 22.04, Windows 11, macOS 13.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import acousto_gen
        2. Create AcousticHologram with...
        3. Call optimize() with...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error-log
    attributes:
      label: Error Messages/Stack Trace
      description: If applicable, add any error messages or stack traces
      render: shell
      placeholder: Paste error messages here...

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Details
      description: If hardware-related, provide details about your transducer array setup
      placeholder: |
        - Array type: UltraLeap256
        - Connection: USB 3.0
        - Power supply: External 12V
        - Other connected devices: ...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear and reproducible example
          required: true
        - label: I have included version information
          required: true