name: Feature Request
description: Suggest a feature for Acousto-Gen
title: "[FEATURE]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
    validations:
      required: true
